### ISSUE TITLE
Any support for multikey keyboard event triggers?

### ISSUE THREAD

**Issue by DerrikCreates** [luttje/Key2Joy#17]
I can't bind multikey stroke keys as a trigger. I want to use shift+key or key+key to trigger an action and it only trigger when those exact keys are pressed/released in combination is this something that is possible? or is this better handled in a lua script?

**Comment by luttje** [comment]
Hey there, good question, thanks for asking it!

Currently there's no support for multi-key triggers. I don't think the scripts support it either.

I'll look into supporting this feature soon. You can expect it to be implemented within a week or so (given that nothing changes in my schedule)

**Comment by luttje** [comment]
I've published the release [0.4.2](https://github.com/luttje/Key2Joy/releases/tag/0.4.2) which now allows you to check if a keyboard key is pressed from scripts. This should help you out a bit.

I'm still intending to allow users to set multiple triggers without having to use scripts. Therefor I'll leave this issue open until I implement that.

## Example
**Goal:** Simulate pressing 'A' on the GamePad only when the user presses A on their keyboard while also holding Shift.

![image](https://user-images.githubusercontent.com/2738114/185788635-14ca4622-d28d-4ca5-933f-5be2181b7ec5.png)

[(View the docs for more example code)](https://github.com/luttje/Key2Joy/blob/0.4.2/Docs/Api/Input/Keyboard.GetKeyDown.md)

**Comment by luttje** [comment]
I added a UI for this in release [0.5.1](https://github.com/luttje/Key2Joy/releases/tag/0.5.1)

![image](https://user-images.githubusercontent.com/2738114/186408946-2c178c83-55ae-4b3b-af69-ba4fe8603a44.png)
