### ISSUE TITLE
Ability to simulate specific joystick angle?

### ISSUE THREAD

**Issue by DerrikCreates** [luttje/Key2Joy#18]
I was trying to find a way to simulate a specific joystick angle. like hold holding the sick to 50% left and so on.

I found the option to simulate a gamepad button as analog but cant find any examples on how to use it in script. 
[SimWinInput supports this ](https://github.com/DavidRieman/SimWinInput#advanced-gamepad-simulation) but I don't know if its exposed to the script api. 

Thanks for the fast response on the multikey support. If I have time I plan on contributing to this project. Its really been a big help

**Comment by luttje** [comment]
Now possible through scripting in [0.4.3](https://github.com/luttje/Key2Joy/releases/tag/0.4.3)

Thanks again!
