### ISSUE TITLE
mapping a keyboard action to "multiple actions" containing keyboard actions sets every keyboard action to the same one

### ISSUE THREAD

**Issue by kokkermanz** [luttje/Key2Joy#26]
unsure of how to say it lol, here what i mean; [link](https://youtu.be/Z8UDoLE0FPU)

**Comment by luttje** [comment]
Oh wow, thank you so much for the video. That makes it super clear what the problem is.

Thanks for taking the time and reporting it!

I'm quite busy the coming days, but might find some time to fix it this weekend.

**Comment by luttje** [comment]
Heya @kokkermanz, I found some time to fix this in [0.5.2](https://github.com/luttje/Key2Joy/releases/tag/0.5.2) :)

Thanks a bunch for reporting so clearly. Hope the tool is more useful to you, now that it works a bit better.

**Comment by kokkermanz** [comment]
thank you!
