### ISSUE TITLE
[Feature Request] Joy2Joy

### ISSUE THREAD

**Issue by totalschaden** [luttje/Key2Joy#40]
Hey, first of all great Software, but sadly it dosnt fit my need yet. Im having the Issue that i want to do Key2Joy (which works great) and at the same time still use my Xbox Controller, but the Target App only Supports Input from 1 Controller.

Is there any chance you could Implement the trigger being a controller with the option already in user config "Override default behaviour when trigger action is executed on/off"
Basicly a Joy2Joy option, so that i can use my controller and keyboard as input for the emulated controller, which i would then use in the target app.

**Comment by luttje** [comment]
Hi, thanks for your input! Please bear with me while I verify if I understand you correctly.

You would like a trigger for Game Controller input (like your Xbox Controller):
![image](https://github.com/luttje/Key2Joy/assets/2738114/1979da6b-c31f-4a51-a53a-190f0c815710)

Then you would configure both keyboard triggers and game controller triggers for the same simulated gamepad:
![image](https://github.com/luttje/Key2Joy/assets/2738114/36878f37-2f71-45cb-a489-5df0be7759e2)

And, using this existing option, would prevent the default keyboard and game controller input from reaching the target app:
![image](https://github.com/luttje/Key2Joy/assets/2738114/a83087a8-79b3-4bad-a13b-dd5826e9ae70)

Is that correct?

**Comment by luttje** [comment]
Cool ideas, both very useful. Thanks!

Sadly I probably won't be able to work on this specific feature for a while. I hope to implement this within 3 months. If it takes longer for me to start and work on this I'll post an update here.

Thanks for your patience.
