### ISSUE TITLE
yo - Mouse movement isn't fully working [ stuttery/skipping/not fully registering ]

### ISSUE THREAD

**Issue by xelmXIV** [luttje/Key2Joy#41]
Not sure if I'm missing something in the instructions or if there's anything i need to adjust, but using the mouse.. it skips and doesn't always register movement even when i turn up my DPI.
so lets say i turn my mouse right for 5 solid seconds.. it might register 1-2 seconds then stop.
it's almost as if something is blocking the mouse movement or it's not fully picking up the connection.

any suggestions or help would be greatly appreciated,

thanks.
~xelm

**Comment by xelmXIV** [comment]
update: after restarting my PC, the mouse doesn't register at all anymore sadly.
i do have DS4 windows, maybe that driver is effecting it? not sure how to get it to register the correct driver.

**Comment by luttje** [comment]
Hi, thanks for reporting this.

I'll try reproduce this when I have time, which I won't have for another month.

Until then sorry for this defect. Thanks again for reporting.

**Comment by luttje** [comment]
PS: after looking into ds4windows I feel that it may send simulated inputs through a channel Key2Joy doesn't listen to. 
It would be super helpful if you could temporarily disable/uninstall ds4windows (dont forget to backup your profiles/settings) to see if it solves the problem. That would help me a ton.

**Comment by luttje** [comment]
Hi @xelmXIV, I'd be interested to know if the problem remains in a newer alpha (`0.7.0-alpha...`) build of this app ([link to releases](https://github.com/luttje/Key2Joy/releases)).

I'll close this issue for now, but if you do find that your problem persists feel free to create a new issue. If you do create a new issue please let me know if the problem persists even with ds4windows fully disabled.

Thanks for your help!
