### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by kabachankun** [luttje/Key2Joy#42]
Anyone know how to fix this problem? It just keeps showing up when I tried to open the app and the app stop working. It was working fine but one time it crashed and this window keeps poppoing up and never fixed. I've tried installing different version, re nstalling, reinstalling windows, but nothing works. Any help? 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Key2Joy.Config.ConfigManager.LoadOrCreate() in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Config\ConfigManager.cs:line 122
   at Key2Joy.Config.ConfigManager.get_Instance() in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Config\ConfigManager.cs:line 23
   at Key2Joy.Mapping.MappingProfile.RestoreLastLoaded() in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Mapping\MappingProfile.cs:line 155
   at Key2Joy.Gui.MainForm.MainForm_Load(Object sender, EventArgs e) in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy.Gui\MainForm.cs:line 177
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Key2Joy
    Assembly Version: 0.6.0.0
    Win32 Version: 0.6.0.0
    CodeBase: file:///C:/Users/kabachan/Downloads/Key2Joy-0.6.0/Key2Joy.exe
----------------------------------------
Key2Joy.Core
    Assembly Version: 0.6.0.0
    Win32 Version: 0.6.0.0
    CodeBase: file:///C:/Users/kabachan/Downloads/Key2Joy-0.6.0/Key2Joy.Core.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
FFMpegCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Users/kabachan/Downloads/Key2Joy-0.6.0/FFMpegCore.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
SimWinGamePad
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1
    CodeBase: file:///C:/Users/kabachan/Downloads/Key2Joy-0.6.0/SimWinGamePad.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.2
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/kabachan/Downloads/Key2Joy-0.6.0/System.Text.Json.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Users/kabachan/Downloads/Key2Joy-0.6.0/ObjectListView.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Users/kabachan/Downloads/Key2Joy-0.6.0/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

![image](https://github.com/luttje/Key2Joy/assets/90488628/4fd84d99-cf47-4d79-a7a5-65b8ec4f1b66)

**Comment by luttje** [comment]
Hi there, thanks for reaching out.

Looks like I made a mistake and caused this. You can probably work around it by renaming the Key2Joy config folder in your Windows user Documents folder to something like "Key2Joy.old".

Let me know if it worked or not. Good luck.

**Comment by kabachankun** [comment]
It worked, Thanks

**Comment by luttje** [comment]
Good to hear!

I'll leave this open as a bug that must be fixed. If the config fails to load it should just give a nice warning and continue to work.

**Comment by kabachankun** [comment]
it's not related to this issue, but I have 1 question. Is there way to disable mouse input completely while key mapping is enabled?

**Comment by luttje** [comment]
Not yet, but I'll make a feature request for you since I've been wanting to rework how input is disabled anyway.

**Comment by kabachankun** [comment]
hmm  yeah. I personally set my mouse movement as right stick. My game keep recognizing my mouse movement and it's not working properly. Anyways, thank you for your help.

**Comment by xMcacutt** [comment]
Hiya, we're looking to use this tool as part of our speedrunning community and members have been running into the same issue. I'm pretty fluent in winforms so I'm happy to have a look if you can point me towards the problem. If you're planning on working on it then I won't step on your toes but just thought I'd mention a fix is desired :)

Thank you for the awesome tool.

**Comment by luttje** [comment]
Hi @xMcacutt, how awesome to hear that a speed running community is looking to use this tool!

Sadly I haven't found the time and energy to work on this and I don't expect to for another couple weeks (perhaps a month). So feel free to work on it, no risk of stepping on my toes.

Any working PR's you submit with fixes or non-breaking changes I'll gladly accept! 

I can't point you in an exact direction, but I believe the error experienced by the original issue poster was caused by an update making a breaking change to the config schema (see Config/ConfigManager)

Thanks for any help and/or contributions, I hugely appreciate it!
