### ISSUE TITLE
Does it work with one of two keyboards?

### ISSUE THREAD

**Issue by klsgh** [luttje/Key2Joy#44]
I am using a USB keypad (https://www.amazon.de/dp/B08V1LZ128) to make some functions of MSFS2020 easily accessible in VR, like setting the pilot position (SPACE) or getting in and out of VR (Ctrl+TAB). However, this device just generates plain keyboard codes, so if the sim window, for some reason, loses focus, the commands don't work any more. So I was wondering if your Key2Joy can be configured such that it only takes keystrokes from this 9-key pad and makes them appear like button presses of a joystick to MSFS2020. The normal keyboard should continue to work normally.

**Comment by klsgh** [comment]
After some more thinking I figured that I can program the Vaydeer keypad with some key sequences that are never used otherwise and react to just these in Key2Joy. So I downloaded Key2Joy and created a new profile with "(keyboard)Press Y + (keyboard) Press LShiftKey" mapped to "Press A on GamePad #0". When I enable mappings in Key2Joy, MSFS2020 offers a new control named "CONTROLLER", in which I mapped the "COCKPIT/EXTERNAL VIEW MODE" to the "A" button.

Now when I press Shift+Y on the keyboard, the camera in the sim switches from cockpit to external, no matter which window (if any) has the focus - great!. Pressing Shift+Y again should switch it back, but it doesn't. I can press Shift+Y as often as I want, with nothing happening. Only after disabling and re-enabling mappings in Key2Joy does it work again, but again only one single time. Looking through the default mappings I figured that I probably also need to define a release mapping, so I added "(keyboard)Release Y + (keyboard) Release LShiftKey" mapped to "Release A on GamePad #0". That didn't help, so I tried "(keyboard)Release Y" (without the LShiftKey) and now it works as expected.

The only thing that is unexpected is that if a command line window (or notepad, anything that echos keypresses) has the focus when I press Shift+Y, the 'Y' character appears in that window. I thought that Key2Joy would "eat" the (mapped) keypresses and not deliver them to any other window. Am I doing something wrong here?

**Comment by luttje** [comment]
Wow, thanks so much for your very clear explanation and own research. I do see a lot that can be improved in Key2Joy, needing to add the release mapping for example feels cumbersome.

On the subject of Key2Joy "eating" input, there should be a configuration (via 'Tools' in the menu strip) to enable this. However I suspect it may be faulty and I'll eventually get to fixing it in #43. So no it's probably not you, but a problem I wrote into Key2Joy.

I'll mark this as a bug and improvement since you highlight a couple things to be fixed and improved.

**Comment by klsgh** [comment]
Glad you liked it.
At http://www.tvdr.de/sim/3/keypad.htm you can see how your great tool solved my problem.
Thanks for sharing your work!
