### ISSUE TITLE
Buttons work once, then stop working

### ISSUE THREAD

**Issue by cherryontopknife** [luttje/Key2Joy#47]
I mapped a few joystick buttons to keys, but the inputs only work once, and seem to randomly work or not work when I use the tester web apps. Sometimes, an input won't work at all. Particularly the X and Y buttons.

I mapped start, back, x and y, to 6, 7, 8, and 9, respectively. I left override on. The issue occurred whether I had another controller connected or not.

My use case is that I use EmulationStation/ RetroBat, and there are a few non-obvious controller shortcuts for saving, loading, and quitting games. I want to map these shortcuts to keyboard keys, and then use a macro pad for saving/ loading/ quitting. It's either that, or somehow documenting the shortcuts near my couch.

This software is exactly what I need, so I'm happy to help in anyway I can! Let me know if there's any other information you need.

**Comment by luttje** [comment]
Hi there, thanks for reporting this possible bug!

Just to check: Did you map the 'release keys' as well for those buttons?

At the moment Key2Joy works a bit finicky, you have to also manually map the 'Release' action as is shown in the default mappings:
![image](https://github.com/luttje/Key2Joy/assets/2738114/a3dedc29-b25e-48e7-95da-6cc69736bd64)

If the problem persists it would help if you could you please share a screenshot of your mappings.

Thanks again!

**Comment by cherryontopknife** [comment]
yup, that fixed it! Awesome. Thank you.

Maybe my reading comprehension skills are lacking, but I didn't notice that mentioned in the README.md. But I probably should have known based on the default mapping.

Closing.

**Comment by luttje** [comment]
It's not your reading, it working like that is just counter intuitive. I'll work on improving it in the future

Great to hear that it's fixed though :)
