### ISSUE TITLE
Mouse input is super janky

### ISSUE THREAD

**Issue by luttje** [luttje/Key2Joy#60]
In #54 I moved the mouse trigger listener to a different system. It seems this has completely broken mouse input for some games. Possibly because games tend to force the cursor into a certain direction if the gamepad stick is moved. When mapping the mouse move to a gamepad stick it just doesn't work and starts spinning me.

I tried it in Portal 1 with version 0.7.0 and immediately had issues after enabling GamePad mode in the options. The character started spinning wildly.

I tried using version 0.6.0 and this did not have the same problem. So I guess we have to try move back to the old system and see if that fixes the problem.

**Comment by luttje** [comment]
Note: the problem of spinning only occurs when these options are enabled:
![image](https://github.com/luttje/Key2Joy/assets/2738114/b5770250-14c1-4993-bd82-7c6961245d39)

That would explain some of the behavior, since #54 forces the cursor to it's old position

**Comment by luttje** [comment]
More observations: It feels like every time the mappings are armed, the input becomes more sensitive

https://github.com/luttje/Key2Joy/assets/2738114/2f22bfe9-c75a-484f-bb5f-d5a4fd83517c

**Comment by luttje** [comment]
Problem and solution described in #63, "fixed" in 6a3d028804c9e72f9aff9f7667266744d0f449a4

**Comment by VC1W** [comment]
> More observations: It feels like every time the mappings are armed, the input becomes more sensitive
> 
>  YIpBz3juzi.mp4

could i get your profile?
